############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Blog"
weight = 2

[[main]]
parent = "Blog"
name = "Blog Posts"
pageRef = "/blog"
weight = 3

[[main]]
parent = "Blog"
weight = 4
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Blog"
weight = 5
name = "Tags"
pageRef = "/tags"

[[main]]
name = "About"
pageRef = "/about"
weight = 6

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 7

[[main]]
weight = 8
name = "Pages"

[[main]]
parent = "Pages"
weight = 9
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Elements"
pageRef = "/elements"
weight = 10

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 11

[[main]]
parent = "Pages"
weight = 12
name = "404 Page"
pageRef = "/404"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Contact"
pageRef = "/contact"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
